site_name: Finauto Docs
site_description: Help and Documentation for Finauto Software
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - header.autohide
  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - toc:
        permalink: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
nav:
  - Home: index.md
  - Client:
      - Introduction: client/intro.md
      - Installation: client/install.md
      - Usage:
          - Basic: client/usage/basic.md
          - Advanced: client/usage/advanced.md
      - Features:
          - Fixed Assets:
            - Register: client/depreciation/fixed_assets.md
          - Share Capital:
            - Import Process: client/sharecapital/importprocess.md
          - Trial Balance:
            - View Ledgers & Stock items : client/trialbalance/trialbalanceview.md
          - Aging:
            - Aging Report : client/aging/agingreport.md
          - Reports:  
            - Accounting Policies : client/reports/accountingpolicies.md
          - Configuration: 
            - Company Master: configuration/companymaster.md
            - Updates      : configuration/updates.md
            - CA Profiles      : configuration/caprofiles.md
            - Settings     : configuration/settings.md
      - FAQ:
          - Common Issues: faq/common-issues.md
                